# Generated by Django 5.2.1 on 2025-11-24 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_course_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='Academic year in format YYYY-YYYY (e.g., 2024-2025)', max_length=20)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester'), ('Summer', 'Summer Semester')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_assignments', to='programs.course')),
                ('instructor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester_courses', to='programs.faculty')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_course_assignments', to='programs.program')),
            ],
            options={
                'ordering': ['academic_year', 'semester', 'course__code'],
                'unique_together': {('academic_year', 'semester', 'course', 'instructor')},
            },
        ),
    ]
