# Generated by Django 5.2.1 on 2025-11-28 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_faculty_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semestercourseassignment',
            options={'ordering': ['academic_year', 'semester', 'instructor__name']},
        ),
        migrations.AlterField(
            model_name='semestercourseassignment',
            name='academic_year',
            field=models.CharField(help_text='Format: 2024-2025', max_length=20),
        ),
        migrations.AlterField(
            model_name='semestercourseassignment',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_assignments', to='programs.faculty'),
        ),
        migrations.AlterField(
            model_name='semestercourseassignment',
            name='program',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semester_assignments', to='programs.program'),
        ),
        migrations.AlterModelTable(
            name='semestercourseassignment',
            table='programs_semestercourseassignment',
        ),
    ]
