# Generated by Django 5.0.7 on 2025-03-25 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Facility',
        ),
    ]
