# Generated by Django 5.1.6 on 2025-02-25 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('faculty_id', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('faculty_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('enrollment_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('users_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('job', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Meetings',
            fields=[
                ('meeting_id', models.AutoField(primary_key=True, serialize=False)),
                ('meeting_name', models.CharField(max_length=100)),
                ('meeting_date', models.DateField()),
                ('department_name', models.CharField(max_length=100)),
                ('meeting_report', models.URLField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.department')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=100)),
                ('program_description', models.TextField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.department')),
            ],
        ),
        migrations.CreateModel(
            name='LearningOutcomes',
            fields=[
                ('outcome_id', models.AutoField(primary_key=True, serialize=False)),
                ('outcome_description', models.TextField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.program')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_name', models.CharField(max_length=100)),
                ('file_type', models.CharField(max_length=20)),
                ('submission_date', models.DateField()),
                ('version', models.IntegerField()),
                ('program_links', models.URLField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.program')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.TextField()),
                ('credits', models.IntegerField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.program')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('assessment_id', models.AutoField(primary_key=True, serialize=False)),
                ('assessment_name', models.CharField(max_length=100)),
                ('assessment_date', models.DateField()),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.program')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Result',
            fields=[
                ('result_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.CharField(max_length=5)),
                ('date', models.DateField()),
                ('comments', models.TextField()),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.assessment')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.student')),
            ],
        ),
        migrations.CreateModel(
            name='Department_Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.course')),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.department')),
            ],
            options={
                'unique_together': {('department_id', 'course_id')},
            },
        ),
        migrations.CreateModel(
            name='Assessment_LearningOutcomes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.assessment')),
                ('outcome_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.learningoutcomes')),
            ],
            options={
                'unique_together': {('assessment_id', 'outcome_id')},
            },
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accreditation.student')),
            ],
            options={
                'unique_together': {('course_id', 'student_id')},
            },
        ),
    ]
