# Generated by Django 5.2.1 on 2025-11-28 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0006_alter_semestercourseassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyllabusUploadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(help_text='e.g., 2024-2025', max_length=20)),
                ('semester', models.CharField(choices=[('First', 'First Semester'), ('Second', 'Second Semester'), ('Summer', 'Summer Semester')], max_length=10)),
                ('course_name', models.CharField(max_length=255)),
                ('is_completed', models.BooleanField(default=False, help_text='Manually marked as complete')),
                ('has_files', models.BooleanField(default=False, help_text='Auto-detected: has files in syllabus folder')),
                ('marked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_syllabi', to=settings.AUTH_USER_MODEL)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus_statuses', to='programs.faculty')),
            ],
            options={
                'verbose_name': 'Syllabus Upload Status',
                'verbose_name_plural': 'Syllabus Upload Statuses',
                'ordering': ['academic_year', 'semester', 'professor__name', 'course_name'],
                'unique_together': {('academic_year', 'semester', 'professor', 'course_name')},
            },
        ),
    ]
