# Generated by Django 5.0.7 on 2025-04-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('Assessment', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Assessment', to='programs.course')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessmentType', models.CharField(max_length=50)),
                ('high', models.FloatField()),
                ('mean', models.FloatField()),
                ('low', models.FloatField()),
                ('grade', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('course_id', models.BigIntegerField()),
                ('instructor_id', models.BigIntegerField()),
                ('description', models.TextField()),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_performances', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentLearningOutcome',
            fields=[
                ('AssesssmentLearningOutcome_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('program_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='assessment.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentLearningOutcome_ABET',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ABETOutcomes_id', models.BigIntegerField()),
                ('LearningOutcome_id', models.BigIntegerField()),
                ('weight', models.IntegerField()),
                ('score', models.IntegerField()),
                ('learning_outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abet_outcomes', to='assessment.assessmentlearningoutcome')),
            ],
        ),
        migrations.CreateModel(
            name='ContinuousImprovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('implementation_date', models.DateField()),
                ('effectiveness_measure', models.TextField()),
                ('weight', models.IntegerField()),
                ('score', models.FloatField()),
                ('action_taken', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuous_improvements', to='assessment.assessment')),
            ],
        ),
    ]
