# Generated by Django 5.0.7 on 2025-04-18 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentlearningoutcome_abet',
            name='level_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
