# Generated by Django 5.0.7 on 2025-04-19 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0002_assessmentlearningoutcome_abet_level_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentlearningoutcome_abet',
            name='ABETOutcomes_id',
        ),
        migrations.RemoveField(
            model_name='assessmentlearningoutcome_abet',
            name='LearningOutcome_id',
        ),
        migrations.RemoveField(
            model_name='assessmentlearningoutcome_abet',
            name='learning_outcome',
        ),
        migrations.RemoveField(
            model_name='assessmentlearningoutcome_abet',
            name='weight',
        ),
        migrations.AddField(
            model_name='assessmentlearningoutcome_abet',
            name='evidence_type',
            field=models.CharField(choices=[('direct', 'Direct'), ('indirect', 'Indirect')], default='direct', max_length=10),
        ),
    ]
