# Generated by Django 5.0.7 on 2025-04-19 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0003_remove_assessmentlearningoutcome_abet_abetoutcomes_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='Assessment',
            new_name='id',
        ),
    ]
