# Generated by Django 5.0.7 on 2025-04-19 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0004_rename_assessment_assessment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABETOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='assessmentlearningoutcome',
            name='abet_outcomes',
            field=models.ManyToManyField(related_name='learning_outcomes', to='assessment.abetoutcome'),
        ),
    ]
