# Generated by Django 5.0.7 on 2025-04-24 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0006_auditlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentlearningoutcome_abet',
            name='abet_outcome',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_scores', to='assessment.abetoutcome'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentlearningoutcome_abet',
            name='assessment_lo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='outcome_scores', to='assessment.assessmentlearningoutcome'),
            preserve_default=False,
        ),
    ]
