# Generated by Django 5.0.7 on 2025-04-24 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0007_assessmentlearningoutcome_abet_abet_outcome_and_more'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='programs.course'),
        ),
    ]
