# Generated by Django 5.0.7 on 2025-04-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0009_assessmentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentevent',
            name='average_score_at_time',
            field=models.FloatField(default=0.0),
        ),
    ]
