# Generated by Django 5.2.1 on 2025-06-05 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0010_assessmentevent_average_score_at_time'),
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ABETComplianceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('course_syllabi', 'Course Syllabi Updated'), ('assessment_data', 'Assessment Data Collected'), ('student_outcomes', 'Student Outcomes Met'), ('faculty_training', 'Faculty Training Complete')], max_length=20, unique=True)),
                ('current_value', models.FloatField(default=0.0)),
                ('target_value', models.FloatField(default=100.0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(default='2024-2025', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='CourseSyllabus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_updated', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2024-2025', max_length=9)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='syllabus', to='programs.course')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('training_type', models.CharField(max_length=100)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('academic_year', models.CharField(default='2024-2025', max_length=9)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to='programs.faculty')),
            ],
        ),
    ]
