# Generated by Django 5.2.1 on 2025-06-08 02:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0011_abetcompliancemetric_coursesyllabus_facultytraining'),
        ('programs', '0002_course_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('exam_questions', 'Exam Questions'), ('project_rubrics', 'Project Rubrics'), ('student_surveys', 'Student Surveys'), ('alumni_feedback', 'Alumni Feedback'), ('lab_reports', 'Lab Reports'), ('capstone_projects', 'Capstone Projects')], max_length=100)),
                ('assessment_type', models.CharField(choices=[('direct', 'Direct Assessment'), ('indirect', 'Indirect Assessment')], max_length=20)),
                ('description', models.TextField()),
                ('target_completion_rate', models.FloatField(default=80.0)),
                ('target_score', models.FloatField(default=3.0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComplianceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('metric_type', models.CharField(choices=[('completion_rate', 'Completion Rate'), ('average_score', 'Average Score'), ('time_to_completion', 'Time to Completion'), ('abet_coverage', 'ABET Outcome Coverage')], max_length=30)),
                ('target_value', models.FloatField()),
                ('current_value', models.FloatField()),
                ('measurement_date', models.DateField(auto_now_add=True)),
                ('semester', models.CharField(default='Fall 2024', max_length=20)),
                ('is_compliant', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssessmentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.BooleanField(default=False)),
                ('score', models.FloatField(blank=True, null=True)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('semester', models.CharField(default='Fall 2024', max_length=20)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessment')),
                ('assessment_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessment.assessmentmethod')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.course')),
            ],
            options={
                'unique_together': {('course', 'assessment_method', 'assessment')},
            },
        ),
    ]
