# Generated by Django 5.2.1 on 2025-06-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0012_assessmentmethod_compliancemetric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultytraining',
            name='completion_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
