# Generated by Django 5.2.1 on 2025-06-15 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0013_alter_facultytraining_completion_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField()),
                ('question_text', models.TextField()),
                ('weight', models.FloatField(help_text='Weight as a percentage (0-100)')),
                ('academic_performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.academicperformance')),
                ('mapped_outcome', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='assessment.abetoutcome')),
            ],
            options={
                'unique_together': {('academic_performance', 'question_no')},
            },
        ),
    ]
