# Generated by Django 5.2.1 on 2025-06-15 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0014_assessmentquestion'),
        ('programs', '0002_course_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentquestion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='programs.course'),
            preserve_default=False,
        ),
    ]
