# Generated by Django 5.2.1 on 2025-06-16 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0015_assessmentquestion_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentquestion',
            name='mapped_outcome',
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='mapped_outcomes',
            field=models.ManyToManyField(blank=True, to='assessment.abetoutcome'),
        ),
    ]
