# Generated by Django 5.2.1 on 2025-06-18 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0016_remove_assessmentquestion_mapped_outcome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='continuousimprovement',
            old_name='assessment_id',
            new_name='assessment',
        ),
    ]
