# Generated by Django 5.2.1 on 2025-11-24 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Administrator'), ('faculty', 'Faculty'), ('evaluator', 'Program Evaluator'), ('professor', 'Professor'), ('HoD', 'HoD'), ('dean', 'Dean')], default='faculty', max_length=20),
        ),
    ]
